package com.easyjet.ei.commercial.claims.processclaim;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class RulesResultObject implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "RULESRESULTOBJECT_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "RULESRESULTOBJECT_ID_GENERATOR", sequenceName = "RULESRESULTOBJECT_ID_SEQ")
   private java.lang.Long id;

   private java.lang.String distruptionResult;

   private java.lang.Long dateDiffInYears;

   private java.lang.Long dateDiffInDays;

   private java.lang.String rule_result;

   private java.lang.String reason;

   private java.lang.Boolean isMealPresentInClaim;

   private java.lang.String rule_exception;

   public RulesResultObject()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getDistruptionResult()
   {
      return this.distruptionResult;
   }

   public void setDistruptionResult(java.lang.String distruptionResult)
   {
      this.distruptionResult = distruptionResult;
   }

   public java.lang.Long getDateDiffInYears()
   {
      return this.dateDiffInYears;
   }

   public void setDateDiffInYears(java.lang.Long dateDiffInYears)
   {
      this.dateDiffInYears = dateDiffInYears;
   }

   public java.lang.Long getDateDiffInDays()
   {
      return this.dateDiffInDays;
   }

   public void setDateDiffInDays(java.lang.Long dateDiffInDays)
   {
      this.dateDiffInDays = dateDiffInDays;
   }

   public java.lang.String getRule_result()
   {
      return this.rule_result;
   }

   public void setRule_result(java.lang.String rule_result)
   {
      this.rule_result = rule_result;
   }

   public java.lang.String getReason()
   {
      return this.reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }

   public java.lang.Boolean getIsMealPresentInClaim()
   {
      return this.isMealPresentInClaim;
   }

   public void setIsMealPresentInClaim(java.lang.Boolean isMealPresentInClaim)
   {
      this.isMealPresentInClaim = isMealPresentInClaim;
   }

   public java.lang.String getRule_exception()
   {
      return this.rule_exception;
   }

   public void setRule_exception(java.lang.String rule_exception)
   {
      this.rule_exception = rule_exception;
   }

   public RulesResultObject(java.lang.Long id, java.lang.String distruptionResult,
         java.lang.Long dateDiffInYears, java.lang.Long dateDiffInDays,
         java.lang.String rule_result, java.lang.String reason,
         java.lang.Boolean isMealPresentInClaim, java.lang.String rule_exception)
   {
      this.id = id;
      this.distruptionResult = distruptionResult;
      this.dateDiffInYears = dateDiffInYears;
      this.dateDiffInDays = dateDiffInDays;
      this.rule_result = rule_result;
      this.reason = reason;
      this.isMealPresentInClaim = isMealPresentInClaim;
      this.rule_exception = rule_exception;
   }

}